FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD my-app.jar /opt/my-app/
EXPOSE 8080
WORKDIR /opt/my-app/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "my-app.jar"]
